library(dplyr)
setwd("Y:/projects/hsienchao/oncogenomics/fusion/fusionTools/data")
ens <- read.table("gencode.v38lift37.canonical.txt", head=T)
v37 <- read.table("gencode.v37lift37.annotation.transcripts.tsv", head=T, fill=T, sep="\t")
joined <- ens %>% dplyr::semi_join(v37, by=c("Ensembl"="transcript_id"))
antijoined <- ens %>% dplyr::anti_join(v37, by=c("Ensembl"="transcript_id"))
ens_old <- read.table("canonical_transcripts_with_ensembl.txt",sep="\t",fill=T,head=T)
in_old <- antijoined %>% inner_join(ens_old, by=c("Symbol"="Symbol"))
in_old <- in_old %>% select(Symbol, Ensembl.y, Canonical, MANE)
colnames(in_old) <- colnames(joined)
in_old$MANE <- "N"
merged <- rbind(joined, in_old)
merged <- merged %>% semi_join(v37, by=c("Ensembl"="transcript_id","Symbol"="gene_name"))
write.table(merged, "gencode.v37lift37.canonical.txt", sep="\t", quote=F, row.names = F)
